---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-shuuji3
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
